CREATE TABLE  "WFF_CARRIER" 
   (        "C_ID" NUMBER NOT NULL ENABLE, 
        "C_NAME" VARCHAR2(25) NOT NULL ENABLE, 
        "C_SHIP_MODE" CHAR(1) NOT NULL ENABLE, 
        "C_FREIGHT_RATE" NUMBER(7,2) NOT NULL ENABLE, 
         PRIMARY KEY ("C_ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "WFF_CUSTOMER" 
   (        "CUST_NO" NUMBER(*,0) NOT NULL ENABLE, 
        "CUST_NAME" VARCHAR2(100) NOT NULL ENABLE, 
        "CUST_BILL_TO_ADDRESS" VARCHAR2(200) NOT NULL ENABLE, 
        "CREDIT_LIMIT" NUMBER(10,2), 
        "BALANCE" NUMBER(10,2), 
        "CUST_SHIP_TO_ADDRESS" VARCHAR2(200), 
         PRIMARY KEY ("CUST_NO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "WFF_ORDERLINE" 
   (        "OL_UPC" NUMBER(*,0) NOT NULL ENABLE, 
        "OL_ORDER_NO" NUMBER(*,0) NOT NULL ENABLE, 
        "OL_QTY" NUMBER(*,0) NOT NULL ENABLE, 
         PRIMARY KEY ("OL_UPC", "OL_ORDER_NO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "WFF_ORDERS" 
   (        "ORDER_NO" NUMBER(*,0) NOT NULL ENABLE, 
        "CUST_NO" NUMBER(*,0) NOT NULL ENABLE, 
        "ACTUAL_SHIP_DATE" DATE, 
        "ORDER_DATE" DATE, 
        "C_ID" NUMBER, 
        "EST_SHIP_DATE" DATE, 
         PRIMARY KEY ("ORDER_NO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "WFF_ORDERS" ADD CONSTRAINT "WFF_FKRESIDESIN" FOREIGN KEY ("C_ID")
          REFERENCES  "WFF_CARRIER" ("C_ID") ENABLE
/

CREATE TABLE  "WFF_PRODUCT" 
   (        "PROD_UPC" NUMBER(*,0) NOT NULL ENABLE, 
        "PROD_DESC" VARCHAR2(50), 
        "PROD_GROUP" NUMBER(*,0), 
        "MSRP" NUMBER, 
        "COST" NUMBER, 
         PRIMARY KEY ("PROD_UPC")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "WFF_PRODUCT" ADD FOREIGN KEY ("PROD_GROUP")
          REFERENCES  "WFF_PRODUCT_GROUP" ("GROUP_NO") ENABLE
/
CREATE TABLE  "WFF_PRODUCT_GROUP" 
   (        "GROUP_NO" NUMBER(*,0) NOT NULL ENABLE, 
        "GROUP_DESC" VARCHAR2(25) NOT NULL ENABLE, 
        "FREEZE_TIME" NUMBER(7,2), 
        "UNITS_PER_CASE" NUMBER(*,0), 
        "WEIGHT_PER_CASE" NUMBER, 
         PRIMARY KEY ("GROUP_NO")
  USING INDEX  ENABLE
   )
/